const Products=[
    {
        name:"Banana",
        price:50,
        img:"https://cdn.pixabay.com/photo/2016/05/30/19/11/banana-1425576_640.png"
    },
    {
        name:"Orange",
        price:50,
        img:"https://png.pngtree.com/png-vector/20231014/ourmid/pngtree-fresh-orange-png-png-image_10159570.png"
    },
    {
        name:"Apple",
        price:50,
        img:"https://static.vecteezy.com/system/resources/thumbnails/020/899/515/small/red-apple-isolated-on-white-png.png"
    },
    {
        name:"Guava",
        price:50,
        img:"https://png.pngtree.com/png-vector/20240715/ourmid/pngtree-guava-on-splash-water-juice-png-image_13104076.png"
    },
    {
        name:"Pineapple",
        price:50,
        img:"https://e7.pngegg.com/pngimages/993/780/png-clipart-pineapple-pineapple-thumbnail.png"
    },
    {
        name:"Pomogranate",
        price:50,
        img:"https://w7.pngwing.com/pngs/885/157/png-transparent-pomegranate-juice-fruit-food-pomegranate-natural-foods-frutti-di-bosco-dried-fruit-thumbnail.png"
    },
    {
        name:"Grapes",
        price:50,
        img:"https://e7.pngegg.com/pngimages/944/390/png-clipart-grape-fruit-kyoho-white-wine-cardinal-grape-grape-natural-foods-frutti-di-bosco-thumbnail.png"
    },
]
export default Products